### ISSUE TITLE
Compare with shoppe

### ISSUE THREAD

**Issue by andreavecy** [tryshopr/shopr#2]
this version has the same features as shoppe but in an updated version?
I have set up a page with shoppe but it is already out of date I would like to know if using shopr is recommended?

**Comment by kirylrb** [comment]
@andreavecy Yes, Shopr is updated to Rails 5 version of Shoppe with Devise authentication implemented.

**Comment by mihado** [comment]
hi @kirylpl are you developing this as part of an organisation or by yourself?

**Comment by kirylrb** [comment]
@mihado It's totally opensource now. You are welcome to join the ship.
